sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  # Post build notifications to the Integrations Flowdock
  flowdock: e3dc17bc8a2c1b3412abe3e5747f8291
  email: false
node_js:
  - '4'
before_install:
  - npm install -g npm@3
  - npm config set loglevel error
  - npm config set cache ./node_modules/.npm
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  - CI=1 MONGODB_VERSION=2.6.x MONGODB_TOPOLOGY=standalone
  # - CI=1 MONGODB_VERSION=3.0.x MONGODB_TOPOLOGY=standalone
  # - CI=1 MONGODB_VERSION=3.1.x MONGODB_TOPOLOGY=standalone
  # - CI=1 MONGODB_VERSION=2.6.x MONGODB_TOPOLOGY=replicaset
  # - CI=1 MONGODB_VERSION=3.0.x MONGODB_TOPOLOGY=replicaset
  # - CI=1 MONGODB_VERSION=3.1.x MONGODB_TOPOLOGY=replicaset
  # - CI=1 MONGODB_VERSION=2.6.x MONGODB_TOPOLOGY=cluster
  # - CI=1 MONGODB_VERSION=3.0.x MONGODB_TOPOLOGY=cluster
  # - CI=1 MONGODB_VERSION=3.1.x MONGODB_TOPOLOGY=cluster
